command 'python C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\NSSDownload\python\retrieveNSS.py C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\NSSDownload 20200201_0000 C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\' return with error (code 1): b'Traceback (most recent call last):\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Modules\\NSSDownload\\python\\retrieveNSS.py", line 121, in <module>\r\n    main()\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Modules\\NSSDownload\\python\\retrieveNSS.py", line 110, in main\r\n    shutil.copy(url,ncTargetDir)\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\shutil.py", line 245, in copy\r\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\shutil.py", line 120, in copyfile\r\n    with open(src, \'rb\') as fsrc:\r\nOSError: [Errno 22] Invalid argument: \'\\\\\\\\ad.unsw.edu.au\\\\OneUNSW\\\\ENG\\\\WRL\\\\WRL1\\\\Coastal\\\\Data\\\\Tide\\\\WL Forecast\\\\BOM Storm Surge\\\\raw\\\\IDZ00154_StormSurge_national_2020020100.nc\'\r\n\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Modules\\NSSDownload\\python\\retrieveNSS.py", line 121, in <module>\r\n    main()\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Modules\\NSSDownload\\python\\retrieveNSS.py", line 110, in main\r\n    shutil.copy(url,ncTargetDir)\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\shutil.py", line 245, in copy\r\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\shutil.py", line 120, in copyfile\r\n    with open(src, \'rb\') as fsrc:\r\nOSError: [Errno 22] Invalid argument: \'\\\\\\\\ad.unsw.edu.au\\\\OneUNSW\\\\ENG\\\\WRL\\\\WRL1\\\\Coastal\\\\Data\\\\Tide\\\\WL Forecast\\\\BOM Storm Surge\\\\raw\\\\IDZ00154_StormSurge_national_2020020100.nc\'\r\n'Traceback (most recent call last):
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Scripts\runForecast\run_forecast_loop.py", line 72, in runModule
    subprocess.check_output(command,shell=True,stderr=subprocess.STDOUT)
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\bin\windows\python\bin\conda-venv\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\bin\windows\python\bin\conda-venv\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\NSSDownload\python\retrieveNSS.py C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\NSSDownload 20200201_0000 C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Scripts\runForecast\run_forecast_loop.py", line 240, in <module>
    main()
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Scripts\runForecast\run_forecast_loop.py", line 160, in main
    runModule(script=retrieveNSSPy,args=arguments)
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Scripts\runForecast\run_forecast_loop.py", line 78, in runModule
    raise RuntimeError("command '{}' return with error (code {}): {}".format(e.cmd, e.returncode, e.output))
RuntimeError: command 'python C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\NSSDownload\python\retrieveNSS.py C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\NSSDownload 20200201_0000 C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\' return with error (code 1): b'Traceback (most recent call last):\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Modules\\NSSDownload\\python\\retrieveNSS.py", line 121, in <module>\r\n    main()\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Modules\\NSSDownload\\python\\retrieveNSS.py", line 110, in main\r\n    shutil.copy(url,ncTargetDir)\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\shutil.py", line 245, in copy\r\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\shutil.py", line 120, in copyfile\r\n    with open(src, \'rb\') as fsrc:\r\nOSError: [Errno 22] Invalid argument: \'\\\\\\\\ad.unsw.edu.au\\\\OneUNSW\\\\ENG\\\\WRL\\\\WRL1\\\\Coastal\\\\Data\\\\Tide\\\\WL Forecast\\\\BOM Storm Surge\\\\raw\\\\IDZ00154_StormSurge_national_2020020100.nc\'\r\n\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Modules\\NSSDownload\\python\\retrieveNSS.py", line 121, in <module>\r\n    main()\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Modules\\NSSDownload\\python\\retrieveNSS.py", line 110, in main\r\n    shutil.copy(url,ncTargetDir)\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\shutil.py", line 245, in copy\r\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\shutil.py", line 120, in copyfile\r\n    with open(src, \'rb\') as fsrc:\r\nOSError: [Errno 22] Invalid argument: \'\\\\\\\\ad.unsw.edu.au\\\\OneUNSW\\\\ENG\\\\WRL\\\\WRL1\\\\Coastal\\\\Data\\\\Tide\\\\WL Forecast\\\\BOM Storm Surge\\\\raw\\\\IDZ00154_StormSurge_national_2020020100.nc\'\r\n'
