No active exception to reraiseTraceback (most recent call last):
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\SurgeDownload_dev\python\process-surge.py", line 79, in <module>
    main()
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\SurgeDownload_dev\python\process-surge.py", line 59, in main
    raise
RuntimeError: No active exception to reraise
