command 'python C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\initFEWSForecast\python\initializeForecast.py C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\ 20210910_0000 NSW C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\initFEWSForecast' return with error (code 1): b'Traceback (most recent call last):\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Modules\\initFEWSForecast\\python\\initializeForecast.py", line 2, in <module>\r\n    from xbfewsTools import fewsForecast\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\site-packages\\xbfewsTools\\__init__.py", line 5, in <module>\r\n    from .preProcess import preProcWatLevs\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\site-packages\\xbfewsTools\\preProcess\\preProcWatLevs.py", line 173\r\n    axis=1)"""\r\n    # TODO: use nearGeom from preprocWaves.py\r\n\r\n    return\r\n        \r\n    """\r\n           ^\r\nSyntaxError: invalid syntax\r\n'Traceback (most recent call last):
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Scripts\runForecast\run_forecast_loop.py", line 83, in runModule
    subprocess.check_output(command,shell=True,stderr=subprocess.STDOUT)
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\bin\windows\python\bin\conda-venv\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\bin\windows\python\bin\conda-venv\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\initFEWSForecast\python\initializeForecast.py C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\ 20210910_0000 NSW C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\initFEWSForecast' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Scripts\runForecast\run_forecast_loop.py", line 283, in <module>
    main()
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Scripts\runForecast\run_forecast_loop.py", line 136, in main
    runModule(script=initializeForecastPy,args=arguments)
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Scripts\runForecast\run_forecast_loop.py", line 89, in runModule
    raise RuntimeError("command '{}' return with error (code {}): {}".format(e.cmd, e.returncode, e.output))
RuntimeError: command 'python C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\initFEWSForecast\python\initializeForecast.py C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\ 20210910_0000 NSW C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\initFEWSForecast' return with error (code 1): b'Traceback (most recent call last):\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Modules\\initFEWSForecast\\python\\initializeForecast.py", line 2, in <module>\r\n    from xbfewsTools import fewsForecast\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\site-packages\\xbfewsTools\\__init__.py", line 5, in <module>\r\n    from .preProcess import preProcWatLevs\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\site-packages\\xbfewsTools\\preProcess\\preProcWatLevs.py", line 173\r\n    axis=1)"""\r\n    # TODO: use nearGeom from preprocWaves.py\r\n\r\n    return\r\n        \r\n    """\r\n           ^\r\nSyntaxError: invalid syntax\r\n'
