command 'python C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\IndicatorsXBeach\indicatorsMain.py C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\IndicatorsXBeach 20200201_0000 C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\ Narrabeen' return with error (code 1): b'Traceback (most recent call last):\r\n  File "fiona/_shim.pyx", line 83, in fiona._shim.gdal_open_vector\r\n  File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer\r\nfiona._err.CPLE_OpenFailedError: C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Forecasts\\20200201_0000\\NSW\\hotspot\\Narrabeen\\XBeach\\postProcess\\ewl_XBeach_points.shp: No such file or directory\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Modules\\IndicatorsXBeach\\indicatorsMain.py", line 166, in <module>\r\n    main()\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Modules\\IndicatorsXBeach\\indicatorsMain.py", line 93, in main\r\n    ewlOverall = gpd.read_file(ewlOverall)\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\site-packages\\geopandas\\io\\file.py", line 160, in _read_file\r\n    with reader(path_or_bytes, **kwargs) as features:\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\site-packages\\fiona\\env.py", line 400, in wrapper\r\n    return f(*args, **kwargs)\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\site-packages\\fiona\\__init__.py", line 256, in open\r\n    c = Collection(path, mode, driver=driver, encoding=encoding,\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\site-packages\\fiona\\collection.py", line 162, in __init__\r\n    self.session.start(self, **kwargs)\r\n  File "fiona/ogrext.pyx", line 540, in fiona.ogrext.Session.start\r\n  File "fiona/_shim.pyx", line 90, in fiona._shim.gdal_open_vector\r\nfiona.errors.DriverError: C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Forecasts\\20200201_0000\\NSW\\hotspot\\Narrabeen\\XBeach\\postProcess\\ewl_XBeach_points.shp: No such file or directory\r\n'Traceback (most recent call last):
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Scripts\runForecast\run_forecast_loop_debug.py", line 72, in runModule
    subprocess.check_output(command,shell=True,stderr=subprocess.STDOUT)
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\bin\windows\python\bin\conda-venv\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\bin\windows\python\bin\conda-venv\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\IndicatorsXBeach\indicatorsMain.py C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\IndicatorsXBeach 20200201_0000 C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\ Narrabeen' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Scripts\runForecast\run_forecast_loop_debug.py", line 242, in <module>
    main()
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Scripts\runForecast\run_forecast_loop_debug.py", line 222, in main
    runModule(script=indicatorsXBeachPy,args=arguments)
  File "C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Scripts\runForecast\run_forecast_loop_debug.py", line 78, in runModule
    raise RuntimeError("command '{}' return with error (code {}): {}".format(e.cmd, e.returncode, e.output))
RuntimeError: command 'python C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\IndicatorsXBeach\indicatorsMain.py C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\Modules\IndicatorsXBeach 20200201_0000 C:\Users\z3531278\Documents\01_FEWS-RegionHome-Aus\ Narrabeen' return with error (code 1): b'Traceback (most recent call last):\r\n  File "fiona/_shim.pyx", line 83, in fiona._shim.gdal_open_vector\r\n  File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer\r\nfiona._err.CPLE_OpenFailedError: C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Forecasts\\20200201_0000\\NSW\\hotspot\\Narrabeen\\XBeach\\postProcess\\ewl_XBeach_points.shp: No such file or directory\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Modules\\IndicatorsXBeach\\indicatorsMain.py", line 166, in <module>\r\n    main()\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Modules\\IndicatorsXBeach\\indicatorsMain.py", line 93, in main\r\n    ewlOverall = gpd.read_file(ewlOverall)\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\site-packages\\geopandas\\io\\file.py", line 160, in _read_file\r\n    with reader(path_or_bytes, **kwargs) as features:\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\site-packages\\fiona\\env.py", line 400, in wrapper\r\n    return f(*args, **kwargs)\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\site-packages\\fiona\\__init__.py", line 256, in open\r\n    c = Collection(path, mode, driver=driver, encoding=encoding,\r\n  File "C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\bin\\windows\\python\\bin\\conda-venv\\lib\\site-packages\\fiona\\collection.py", line 162, in __init__\r\n    self.session.start(self, **kwargs)\r\n  File "fiona/ogrext.pyx", line 540, in fiona.ogrext.Session.start\r\n  File "fiona/_shim.pyx", line 90, in fiona._shim.gdal_open_vector\r\nfiona.errors.DriverError: C:\\Users\\z3531278\\Documents\\01_FEWS-RegionHome-Aus\\Forecasts\\20200201_0000\\NSW\\hotspot\\Narrabeen\\XBeach\\postProcess\\ewl_XBeach_points.shp: No such file or directory\r\n'
